### ISSUE TITLE
qti.tvm.error.OpNotImplemented: The following operators are not supported in frontend TFLite: 'GELU'

### ISSUE THREAD

**Issue by chenxiao521** [quic/ai-hub-models#104]
snpe-tflite-to-dlc --input_network sam-samencoder.tflite --input_dim "image" 1,1024,1024,3 --output_path samen.dlc
2024-10-13 16:56:14,218 - 230 - ERROR - Encountered Error: The following operators are not supported in frontend TFLite: 'GELU'

Traceback (most recent call last):
  File "/opt/qcom/aistack/qairt/2.27.0.240926/bin/x86_64-linux-clang/snpe-tflite-to-dlc", line 52, in main
    converter = TFLiteConverterFrontend(args)
  File "/opt/qcom/aistack/qairt/2.27.0.240926/lib/python/qti/aisw/converters/tflite/tflite_to_ir.py", line 24, in __init__
    super(TFLiteConverterFrontend, self).__init__(args,
  File "/opt/qcom/aistack/qairt/2.27.0.240926/lib/python/qti/aisw/converters/relay/relay_to_ir.py", line 323, in __init__
    self.importer.convert_to_relay(self.input_model_path,
  File "/opt/qcom/aistack/qairt/2.27.0.240926/lib/python/qti/aisw/converters/relay/importers/tflite_importer.py", line 115, in convert_to_relay
    self.mod, self.params = tflite_to_relay.from_tflite(tflite_model,
  File "/opt/qcom/aistack/qairt/2.27.0.240926/lib/python/qti/tvm/relay/frontend/tflite.py", line 4639, in from_tflite
    op_converter.check_unsupported_ops(custom_op_factory)
  File "/opt/qcom/aistack/qairt/2.27.0.240926/lib/python/qti/tvm/relay/frontend/tflite.py", line 269, in check_unsupported_ops
    raise tvm.error.OpNotImplemented(raise_msg)
qti.tvm.error.OpNotImplemented: The following operators are not supported in frontend TFLite: 'GELU'

**Comment by mestrona-3** [comment]
Hi @chenxiao521 , this repo is specific to questions about Qualcomm AI Hub. We currently don't support DLC, and though this is in our plans for the future, we don't have a timeline. Can you try reaching out via Qualcomm Developer Discord, they may have a better answer on why you're hitting this issue. https://discord.gg/akBfTuX2bR
