### ISSUE TITLE
[BUG] Error exporting OpenAI-Clip

### ISSUE THREAD

**Issue by rachillesf** [quic/ai-hub-models#110]
Im trying to test the export of openAI clip model and getting the following error 

`RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'`

**To Reproduce**
Install the package via pip: `pip install "qai_hub_models[openai_clip]"`

Run export command: `python -m qai_hub_models.models.openai_clip.export`

**Stack trace**
``
2024-10-29 12:44:31,668 - root - INFO - AIMET
Traceback (most recent call last):
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/models/openai_clip/export.py", line 244, in <module>
    main()
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/models/openai_clip/export.py", line 240, in main
    export_model(**vars(args))
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/models/openai_clip/export.py", line 133, in export_model
    source_model = torch.jit.trace(
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/jit/_trace.py", line 759, in trace
    return trace_module(
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/jit/_trace.py", line 976, in trace_module
    module._c._create_method_from_trace(
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/utils/base_model.py", line 178, in __call__
    return torch.nn.Module.__call__(self, *args, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/models/openai_clip/model.py", line 93, in forward
    text_features = self.net.encode_text(clipped_text)
  File "/home/rachillesf/.qaihm/models/openai_clip/v1/openai_CLIP_git/clip/model.py", line 348, in encode_text
    x = self.transformer(x)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/rachillesf/.qaihm/models/openai_clip/v1/openai_CLIP_git/clip/model.py", line 203, in forward
    return self.resblocks(x)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/rachillesf/.qaihm/models/openai_clip/v1/openai_CLIP_git/clip/model.py", line 190, in forward
    x = x + self.attention(self.ln_1(x))
  File "/home/rachillesf/.qaihm/models/openai_clip/v1/openai_CLIP_git/clip/model.py", line 187, in attention
    return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 1167, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/torch/nn/functional.py", line 5046, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
  File "/home/rachillesf/anaconda3/envs/aihub2/lib/python3.8/site-packages/qai_hub_models/models/openai_clip/model.py", line 191, in patched_in_projection_packed
    proj = F.linear(q, w, b)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
``

**Host configuration:**
 - OS and version: Ubuntu 20.04
 - Python 3.8.2

**Comment by kory** [comment]
I am unable to reproduce this issue on Ubuntu 22.04 and python 3.8.2. 

Could you try installing torch CPU? 
```
pip install http://download.pytorch.org/whl/cpu/torch-2.1.2%2Bcpu-cp38-cp38-linux_x86_64.whl\#sha256\=c4620b08e9b8572594861ebedaf739d86801068a48c0399cbdf6559d1d351789
```
