### ISSUE TITLE
[BUG] YoLo (and other models) DEMO not working - dataset folder is locally available but reference is not correct

### ISSUE THREAD

**Issue by BrickDesignerNL** [quic/ai-hub-models#114]
**Describe the bug**
After executing the work-a-round with Python 3.10.11 (AMD64) in https://github.com/quic/ai-hub-models/issues/113 the `py -m pip install "qai_hub_models[yolov7]"` did run, but `py -m qai_hub_models.models.yolov7.demo` gives the following error.

**Stack trace**
```
Traceback (most recent call last):
  File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\<user_name>\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\models\yolov7\demo.py", line 5, in <module>
    from qai_hub_models.models._shared.yolo.demo import yolo_detection_demo
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\models\_shared\yolo\demo.py", line 12, in <module>
    from qai_hub_models.utils.args import (
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\utils\args.py", line 29, in <module>
    from qai_hub_models.utils.inference import OnDeviceModel, compile_model_from_args
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\utils\inference.py", line 23, in <module>
    from qai_hub_models.utils.qai_hub_helpers import (
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\utils\qai_hub_helpers.py", line 18, in <module>
    from qai_hub_models.utils.config_loaders import QAIHMModelPerf
  File "C:\Users\<user_name>\python\qai_hub_models_env_py310\lib\site-packages\qai_hub_models\utils\config_loaders.py", line 16, in <module>
    from datasets import get_dataset_infos
ModuleNotFoundError: No module named 'datasets'
```

**Where is the datasets folder?**
`C:\Users\<user_name>\python\qai_hub_models_env_py310\Lib\site-packages\qai_hub_models\datasets`
and it's content is equal to https://github.com/quic/ai-hub-models/tree/main/qai_hub_models/datasets

**Only for YoLo?**
No also for Whisper - and probably others.

**Host configuration:**
 - OS and version: Windows 11 ARM64, cmd.exe
 - Python: 3.10.11 amd64

**Comment by kory** [comment]
Thanks for the report. This requirement is missing in our dependencies file. Try `pip install datasets==2.14.5` to resolve this.

We will fix this in our next release.
