### ISSUE TITLE
[BUG] exporting long context for LLMs conversion failure

### ISSUE THREAD

**Issue by Zant12** [quic/ai-hub-models#142]
**Describe the bug**
When converting models for long contexts `--context-length 65536` , The online convert job is currently fails produce  some "token" models, when exporting, e.g: `python -m qai_hub_models.models.llama_v3_2_3b_chat_quantized.export`
**To Reproduce**
python -m qai_hub_models.models.llama_v3_2_3b_chat_quantized.export --chipset qualcomm-snapdragon-8-elite --skip-inferencing --skip-profiling --context-length 65536 --output-dir genie_bundle_llama_v3_2_3b_chat_65536/

**Stack trace**

```
Uploading llama_v3_2_3b_chat_quantized_token_3_of_3.aimet.zip part 1 of 4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00G/1.00G [00:57<00:00, 18.8MB/s]
Uploading llama_v3_2_3b_chat_quantized_token_3_of_3.aimet.zip part 2 of 4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00G/1.00G [00:53<00:00, 20.2MB/s]
Uploading llama_v3_2_3b_chat_quantized_token_3_of_3.aimet.zip part 3 of 4
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00G/1.00G [01:14<00:00, 14.4MB/s]
Uploading llama_v3_2_3b_chat_quantized_token_3_of_3.aimet.zip part 4 of 4
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512M/512M [00:27<00:00, 19.7MB/s]
Scheduled compile job (jgo2dvqqp) successfully. To see the status and results:
    https://app.aihub.qualcomm.com/jobs/jgo2dvqqp/

Waiting for compile job (jgn61e2k5) completion. Type Ctrl+C to stop waiting at any time.
    ❌ FAILED               Internal compiler error            
Waiting for compile job (jp3jom33g) completion. Type Ctrl+C to stop waiting at any time.
    ✅ SUCCESS                          
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/user/llm_on_genie_venv/lib/python3.10/site-packages/qai_hub_models/models/llama_v3_2_3b_chat_quantized/export.py", line 57, in <module>
    main()
  File "/home/user/llm_on_genie_venv/lib/python3.10/site-packages/qai_hub_models/models/llama_v3_2_3b_chat_quantized/export.py", line 46, in main
    export_model(
  File "/home/user/llm_on_genie_venv/lib/python3.10/site-packages/qai_hub_models/models/_shared/llama3/export.py", line 238, in export_model
    link_job = hub.submit_link_job(models, name=full_name)
  File "/home/user/llm_on_genie_venv/lib/python3.10/site-packages/qai_hub/client.py", line 4455, in submit_link_job
    model.producer is None
AttributeError: 'NoneType' object has no attribute 'producer'
```
[jgn61e2k5.log](https://github.com/user-attachments/files/18162978/jgn61e2k5.log)

**Host configuration:**
 - OS and version: Ubuntu
 - QAI-Hub-Models version:  
 - QAI-Hub client version: qualcomm_ai_engine_direct.2.28.2.241116.Linux-AnyCPU_QNN

**Comment by gustavla** [comment]
Hi @Zant12,

That is a very long context length indeed that I do not anticipate will work for a variety of reasons. You are hitting a time-limit in the compilation jobs (which makes sense, compilation time will likely increase with context length due to tiling, etc.). If you didn't hit a time limit issue, I am sure there would be other issues downstream. Even if we could successfully compile the model asset, all devices I can think of would not be able to run it.

For now, we only support context lengths up to 4096. You may be able to increase it a little bit for some models and devices, but I do not anticipate any device supporting x16 longer context length. Sorry about that!
