### ISSUE TITLE
[BUG] `podm` package not found

### ISSUE THREAD

**Issue by mbenencase** [quic/ai-hub-models#144]
**Describe the bug**

After installing `pip3 install "qai_hub_models[yolov8_det_quantized]"`

```
ModuleNotFoundError: No module named 'podm.metrics'
```

**To Reproduce**
1. Created a new virtual env with `python3 -m venv env && source env/bin/activate`
2. Installed `pip3 install qai_hub_models && pip3 install "qai_hub_models[yolov8_det_quantized]"
3. After that, I need to install `pip3 install ultralytics`
4. After trying to run `python -m qai_hub_models.models.yolov8_det_quantized.demo`, I received the following error:

```
(env) dtlabs@dtw4:~/projects/ai-hub$ python -m qai_hub_models.models.yolov8_det_quantized.demo
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det_quantized/__init__.py", line 5, in <module>
    from qai_hub_models.models.yolov8_det.app import YoloV8DetectionApp as App  # noqa: F401
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det/__init__.py", line 6, in <module>
    from .model import MODEL_ID  # noqa: F401
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det/model.py", line 11, in <module>
    from qai_hub_models.evaluators.detection_evaluator import DetectionEvaluator
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/evaluators/detection_evaluator.py", line 10, in <module>
    from podm.metrics import (  # type: ignore
ModuleNotFoundError: No module named 'podm'
```

5. I tried to install `pip3 install podm`, but received:

```
(env) dtlabs@dtw4:~/projects/ai-hub$ python -m qai_hub_models.models.yolov8_det_quantized.demo
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det_quantized/__init__.py", line 5, in <module>
    from qai_hub_models.models.yolov8_det.app import YoloV8DetectionApp as App  # noqa: F401
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det/__init__.py", line 6, in <module>
    from .model import MODEL_ID  # noqa: F401
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/models/yolov8_det/model.py", line 11, in <module>
    from qai_hub_models.evaluators.detection_evaluator import DetectionEvaluator
  File "/home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages/qai_hub_models/evaluators/detection_evaluator.py", line 10, in <module>
    from podm.metrics import (  # type: ignore
ModuleNotFoundError: No module named 'podm.metrics'

```

**Expected behavior**
I expected that the command `pip3 install "qai_hub_models[yolov8_det_quantized]"` installed all the necessary dependencies.

**Stack trace**
Added previously.

**Host configuration:**
 - Ubuntu 22.04
(env) dtlabs@dtw4:~/projects/ai-hub$ python3
Python 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qai_hub
>>> qai_hub.__version__
'0.20.1'

**Comment by kory** [comment]
Can you `pip show object-detection-metrics`? What's the output?

This is where `podm` comes from. It's included in the requirements for YOLOv8 (https://github.com/quic/ai-hub-models/blob/main/qai_hub_models/models/yolov8_det_quantized/requirements.txt).

**Comment by mbenencase** [comment]
@kory this is the output:

```
Name: object-detection-metrics
Version: 0.4.post1
Summary: Object Detection Metrics
Home-page: https://github.com/yfpeng/object_detection_metrics
Author: Yifan Peng
Author-email: yip4002@med.cornell.edu
License: MIT License
Location: /home/dtlabs/projects/ai-hub/env/lib/python3.10/site-packages
Requires: docopt, matplotlib, numpy, pandas, Pillow, pycocotools, scikit-image, tqdm
Required-by:
```

However, I fixed my env by installing `pip3 install numpy==1.23.5`. Now I didn't face any other problem. When I installed the `qai_hub_models` package, it installed `numpy==2.2.0`. And that version was breaking the environment when I tried to use yolov8 export.

**Comment by kory** [comment]
Great find!

Could you walk us through the exact steps you took? Was it on a completely fresh environment?

Our [requirements state](https://github.com/quic/ai-hub-models/blob/9857d3ffe0df7946040aec35628e1f6582b03095/qai_hub_models/requirements.txt#L6) numpy < 2.0 should be installed. Something odd is going on here.

I appreciate your help diagnosing the root cause.

**Comment by mbenencase** [comment]
@kory I investigated the NumPy required by qai-hub and ultralytics, so give it a shot installing numpy < 2.0.

Here's my `pip3 freeze`:

```
absl-py==2.1.0
aimet-torch==1.32.1.post1
aiofiles==24.1.0
aiohappyeyeballs==2.4.4
aiohttp==3.11.11
aiosignal==1.3.2
anyio==4.7.0
argcomplete==3.5.2
asttokens==3.0.0
astunparse==1.6.3
async-timeout==5.0.1
attrs==24.3.0
backcall==0.2.0
backoff==2.2.1
beautifulsoup4==4.12.3
bleach==6.2.0
bokeh==3.2.2
boto3==1.35.85
botocore==1.35.85
Brotli==1.1.0
cachetools==5.5.0
ccimport==0.4.4
certifi==2024.12.14
charset-normalizer==3.4.0
clarabel==0.9.0
colorcet==3.1.0
coloredlogs==15.0.1
contextlib2==21.6.0
contourpy==1.3.1
cumm==0.7.11
cvxpy==1.6.0
cycler==0.12.1
cylp==0.92.3
dacite==1.7.0
dataclasses==0.6
datasets==2.14.5
decorator==5.1.1
Deprecated==1.2.15
deprecation==2.1.0
dill==0.3.7
dnspython==2.7.0
docopt==0.6.2
exceptiongroup==1.2.2
executing==2.1.0
fiftyone==1.1.0
fiftyone-brain==0.18.2
fiftyone_db==1.1.7
filelock==3.16.1
fire==0.7.0
flatbuffers==24.3.25
fonttools==4.55.3
frozenlist==1.5.0
fsspec==2023.6.0
ftfy==6.3.1
future==1.0.0
gast==0.4.0
gdown==4.7.1
gitdb==4.0.11
GitPython==3.1.42
glob2==0.7
google-auth==2.37.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
graphql-core==3.2.5
grpcio==1.68.1
h11==0.14.0
h2==4.1.0
h5py==3.12.1
holoviews==1.18.3
hpack==4.0.0
httpcore==1.0.7
httpx==0.28.1
huggingface-hub==0.23.5
humanfriendly==10.0
humanize==4.11.0
hvplot==0.9.2
Hypercorn==0.17.3
hyperframe==6.0.1
hypothesis==6.122.5
idna==3.10
imageio==2.36.1
inflate64==1.0.0
ipython==8.12.3
jax==0.4.30
jaxlib==0.4.30
jedi==0.19.2
Jinja2==3.0.3
jmespath==1.0.1
joblib==1.4.2
jsonlines==4.0.0
jsonschema==4.23.0
jsonschema-specifications==2024.10.1
kaleido==0.2.1
keras==2.12.0
kiwisolver==1.4.7
lark==1.2.2
lazy_loader==0.4
libclang==18.1.1
linkify-it-py==2.0.3
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.10.0
matplotlib-inline==0.1.7
mdit-py-plugins==0.4.2
mdurl==0.1.2
ml_dtypes==0.5.0
mongoengine==0.24.2
motor==3.5.3
mpmath==1.3.0
multidict==6.1.0
multiprocess==0.70.15
multivolumefile==0.2.3
networkx==3.4.2
ninja==1.11.1.3
numpy==1.23.5
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
object-detection-metrics==0.4.post1
onnx==1.14.1
onnxruntime==1.15.1
onnxruntime_extensions==0.13.0
onnxsim==0.4.36
opencv-python==4.10.0.84
opencv-python-headless==4.10.0.84
opt_einsum==3.4.0
osqp==0.6.7.post3
packaging==24.2
pandas==1.5.3
panel==1.3.8
param==2.2.0
parso==0.8.4
pccm==0.4.16
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.0.0
plotly==5.24.1
podm==0.0.19
portalocker==3.0.0
pprintpp==0.4.0
prettytable==3.11.0
priority==2.0.0
progressbar2==4.5.0
prompt_toolkit==3.0.48
propcache==0.2.1
protobuf==4.25.5
psutil==6.1.1
ptyprocess==0.7.0
pure_eval==0.2.3
py-cpuinfo==9.0.0
py7zr==0.22.0
pyarrow==18.1.0
pyasn1==0.6.1
pyasn1_modules==0.4.1
pybcj==1.0.2
pybind11==2.13.6
pycocotools==2.0.8
pycryptodomex==3.21.0
pydash==8.0.4
Pygments==2.18.0
pymongo==4.8.0
pyparsing==3.2.0
pyppmd==1.1.0
PySocks==1.7.1
python-dateutil==2.9.0.post0
python-utils==3.9.1
pytz==2024.2
pyviz_comms==3.0.3
PyYAML==6.0.2
pyzstd==0.16.2
qai-hub==0.20.1
qai-hub-models==0.20.0
qdldl==0.1.7.post4
rarfile==4.2
referencing==0.35.1
regex==2024.11.6
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
retrying==1.3.4
rich==13.9.4
rpds-py==0.22.3
rsa==4.9
Rtree==1.3.0
s3transfer==0.10.4
schema==0.7.5
scikit-image==0.25.0
scikit-learn==1.1.3
scipy==1.14.1
scs==3.2.7
seaborn==0.13.2
semver==3.0.2
shapely==2.0.6
six==1.17.0
smmap==5.0.1
sniffio==1.3.1
sortedcontainers==2.4.0
soupsieve==2.6
spconv==2.3.8
sse-starlette==0.10.3
sseclient-py==1.8.0
stack-data==0.6.3
starlette==0.42.0
strawberry-graphql==0.255.0
sympy==1.13.3
tabulate==0.9.0
taskgroup==0.2.1
tenacity==9.0.0
tensorboard==2.12.3
tensorboard-data-server==0.7.2
tensorboardX==2.4
tensorflow==2.12.0
tensorflow-estimator==2.12.0
tensorflow-io-gcs-filesystem==0.37.1
termcolor==2.5.0
texttable==1.7.0
threadpoolctl==3.5.0
tifffile==2024.12.12
tomli==2.2.1
torch==2.1.2
torchvision==0.16.2
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
triton==2.1.0
typing_extensions==4.12.2
tzdata==2024.2
tzlocal==5.2
uc-micro-py==1.0.3
ultralytics==8.3.52
ultralytics-thop==2.0.13
universal-analytics-python3==1.1.1
urllib3==2.2.3
voxel51-eta==0.13.1
wcwidth==0.2.13
webencodings==0.5.1
Werkzeug==3.1.3
wrapt==1.14.1
wsproto==1.2.0
xmltodict==0.14.2
xxhash==3.5.0
xyzservices==2024.9.0
yarl==1.18.3
```

**Comment by gustavla** [comment]
@kory Don't you think this is a case of dashes-vs-underscores in the pip extra?

There is a known problem in pip that makes underscores not work well in pip extra entries, even if they are represented in the setup.py. Long story short, please try:

```
pip install qai-hub-models[yolov8-det-quantized]
```
The dashes between qai and hub and models are actually fine either as dashes or underscores, but the ones in `[...]` MUST be dashes (or will be silently ignored, so the dependencies won't be picked up).

Our READMEs all have the mistake of underscores. This will be fixed in our next released, which is scheduled for today.

**Comment by mestrona-3** [comment]
@kory fixed this with yesterday's release. @mbenencase I'll close this issue and please re-open if you're still experiencing issues.
