### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'ffnet_datasets'

### ISSUE THREAD

**Issue by LawrenceMeng** [quic/ai-hub-models#45]
**Describe the bug**

**To Reproduce**
1. 从QC AI-HUB 模型库中，下载预训练模型，这里的以ffnet_40s为例
pip3 install "qai-hub-models[ffnet_40s]"
2. 使用python 脚本运行demo
python -m qai_hub_models.models.ffnet_40s.demo

and error is:
(aihub) ts@ubuntu20:~/data/sdkmanager/aihub/ai-hub-models$ python -m qai_hub_models.modelsdel.ffnet_40s.demo
/home/ts/anaconda3/envs/aihub/bin/python: Error while finding module specification for 'qai_hub_models.modelsdel.ffnet_40s.demo' (ModuleNotFoundError: No module named 'qai_hub_models.modelsdel')
(aihub) ts@ubuntu20:~/data/sdkmanager/aihub/ai-hub-models$ python -m qai_hub_models.models.ffnet_40s.demo
Loading pretrained model state dict from /home/ts/.qaihm/models/ffnet/v1/ffnet40S/ffnet40S_dBBB_cityscapes_state_dict_quarts.pth
Initializing ffnnet40S_dBBB_mobile weights
Traceback (most recent call last):
  File "/home/ts/anaconda3/envs/aihub/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ts/anaconda3/envs/aihub/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ts/data/sdkmanager/aihub/ai-hub-models/qai_hub_models/models/ffnet_40s/demo.py", line 16, in <module>
    main()
  File "/home/ts/data/sdkmanager/aihub/ai-hub-models/qai_hub_models/models/ffnet_40s/demo.py", line 12, in main
    cityscapes_segmentation_demo(FFNet40S, MODEL_ID, is_test=is_test)
  File "/home/ts/data/sdkmanager/aihub/ai-hub-models/qai_hub_models/models/_shared/cityscapes_segmentation/demo.py", line 64, in cityscapes_segmentation_demo
    app = CityscapesSegmentationApp(inference_model)
  File "/home/ts/data/sdkmanager/aihub/ai-hub-models/qai_hub_models/models/_shared/cityscapes_segmentation/app.py", line 97, in __init__
    self.color_mapping = _load_cityscapes_loader().dataset.color_mapping
  File "/home/ts/data/sdkmanager/aihub/ai-hub-models/qai_hub_models/models/_shared/cityscapes_segmentation/app.py", line 57, in _load_cityscapes_loader
    from ffnet_datasets.cityscapes.dataloader.get_dataloaders import (
ModuleNotFoundError: No module named 'ffnet_datasets'

**Expected behavior**

**Comment by mestrona-3** [comment]
Hi @LawrenceMeng, this should have been fixed with our latest release on Tuesday May 28th. Can you please re-try with AI Hub Models 0.70? Thanks!
